# Generated by Django 3.2.25 on 2024-09-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_optimizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='productimage',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
